### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shikulja** [refaim/MissingTradeSkillsList#47] opened 2023-07-26 16:48 UTC
using Vanilla (1.12) client and vanilla version of addon
error on load

<img width="500" alt="image" src="https://github.com/refaim/MissingTradeSkillsList/assets/3386359/0740ec7d-f927-45c0-beff-81771852a104">

**Comment by shikulja** [comment] 2023-07-26 17:11
disable all addons. error the same
<img width="552" alt="image" src="https://github.com/refaim/MissingTradeSkillsList/assets/3386359/7f254262-cfe4-4675-9fb2-0ac9e5959535">

**Comment by shikulja** [comment] 2023-07-26 17:20
<img width="507" alt="image" src="https://github.com/refaim/MissingTradeSkillsList/assets/3386359/c8fbf45a-2a11-4051-a525-94a09b19d010">
everlook

**Comment by refaim** [comment] 2023-10-05 15:43
> disable all addons. error the same <img alt="image" width="552" src="https://user-images.githubusercontent.com/3386359/256311161-7f254262-cfe4-4675-9fb2-0ac9e5959535.png">

Couldn't reproduce on Everlook using latest version.

**Comment by refaim** [comment] 2023-10-05 15:45
> <img alt="image" width="507" src="https://user-images.githubusercontent.com/3386359/256313196-c8fbf45a-2a11-4051-a525-94a09b19d010.png">

Will be fixed in https://github.com/refaim/MissingTradeSkillsList/issues/48

**Closed** 2024-11-09 17:55 UTC
Labels: question
